swagger: "2.0"
info:
  version: 1.0.0
  title: aws-s3
  description: My cool TypeScript app
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  FileBody:
    type: object
    title: file
    required:
      - file
    properties:
      base64:
        type: string
      key:
        type: string

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples
  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found
  /files:
    get:
      tags:
        - Files
      description: Fetch all files
      responses:
        200:
          description: Returns all files
    post:
      tags:
        - Files
      description: Save/Update a new files
      parameters:
        - name: files
          in: body
          description: an files
          required: true
          schema: 
            $ref: "#/definitions/FileBody"
      responses:
        200:
          description: Returns all files
  /files/{id}:
    get:
      tags:
        - Files
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the file to retrieve
          type: string
      responses:
        200:
          description: Return the base64 file with the specified id and the content type
        404:
          description: File not found
    delete:
      tags:
        - Files
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the file to retrieve
          type: string
      responses:
        200:
          description: Return the file with the specified id
        404:
          description: File not found
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification